name: test

on:
  push:  
  workflow_dispatch:

jobs:
  test-micromamba:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: mamba-org/setup-micromamba@v1
        with:
          init-shell: bash
          environment-name: test-env
          create-args: >-
            python=3.11
      - name: Check environment and Python version
        run: |
          python --version
          micromamba --version
          micromamba activate test-env
          python --version
          printenv
